language: php

php:
  - 7.4

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    on_success: never
    on_fail: always